version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: controle_estoque_db
    environment:
      POSTGRES_DB: controle_estoque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
